//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAccount.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankAccount.I18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account Number can not blank.
        /// </summary>
        public static string Validator_Account_Account_Number {
            get {
                return ResourceManager.GetString("Validator_Account_Account_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account Balance can not be empty.
        /// </summary>
        public static string Validator_Account_Balance {
            get {
                return ResourceManager.GetString("Validator_Account_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account Balance can not be less than 100 USD.
        /// </summary>
        public static string Validator_Account_Minimum_Balance {
            get {
                return ResourceManager.GetString("Validator_Account_Minimum_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account Routing Number can not be blank.
        /// </summary>
        public static string Validator_Account_Routing_Number {
            get {
                return ResourceManager.GetString("Validator_Account_Routing_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account User ID can not blank.
        /// </summary>
        public static string Validator_Account_UserId {
            get {
                return ResourceManager.GetString("Validator_Account_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email is invalid.
        /// </summary>
        public static string Validator_User_Email_Format {
            get {
                return ResourceManager.GetString("Validator_User_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name is required.
        /// </summary>
        public static string Validator_User_FirstName {
            get {
                return ResourceManager.GetString("Validator_User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name must be between 1 and 50 characters in length.
        /// </summary>
        public static string Validator_User_FirstName_Length {
            get {
                return ResourceManager.GetString("Validator_User_FirstName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name is required.
        /// </summary>
        public static string Validator_User_LastName {
            get {
                return ResourceManager.GetString("Validator_User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name must be between 1 and 50 characters in length.
        /// </summary>
        public static string Validator_User_LastName_Length {
            get {
                return ResourceManager.GetString("Validator_User_LastName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password is required.
        /// </summary>
        public static string Validator_User_Password {
            get {
                return ResourceManager.GetString("Validator_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must be between 8 and 50 characters in length.
        /// </summary>
        public static string Validator_User_Password_Length {
            get {
                return ResourceManager.GetString("Validator_User_Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone is invalid.
        /// </summary>
        public static string Validator_User_Phone_Format {
            get {
                return ResourceManager.GetString("Validator_User_Phone_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Phone must be 10 digits in length.
        /// </summary>
        public static string Validator_User_Phone_Length {
            get {
                return ResourceManager.GetString("Validator_User_Phone_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username is required.
        /// </summary>
        public static string Validator_User_Username {
            get {
                return ResourceManager.GetString("Validator_User_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username must be between 5 and 50 characters in length.
        /// </summary>
        public static string Validator_User_Username_Length {
            get {
                return ResourceManager.GetString("Validator_User_Username_Length", resourceCulture);
            }
        }
    }
}
